"""create notifications table

Revision ID: 01cfae4fbc76
Revises: b375a49efe32
Create Date: 2026-07-10 18:58:29.717924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cfae4fbc76'
down_revision: Union[str, Sequence[str], None] = 'b375a49efe32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recipient_type', sa.String(length=50), nullable=False),
    sa.Column('consumer_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(recipient_type = 'consumer' AND consumer_id IS NOT NULL AND user_id IS NULL) OR (recipient_type = 'personnel' AND user_id IS NOT NULL AND consumer_id IS NULL)", name='ck_notifications_exactly_one_recipient'),
    sa.CheckConstraint("recipient_type IN ('consumer', 'personnel')", name='ck_notifications_recipient_type'),
    sa.CheckConstraint('(is_read = false AND read_at IS NULL) OR (is_read = true AND read_at IS NOT NULL)', name='ck_notifications_read_pair'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumer_account_table.consumer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
