"""create_verification_history_table

Revision ID: 095a09c0561b
Revises: e6cf30432b43
Create Date: 2026-07-03 19:45:22.390312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '095a09c0561b'
down_revision: Union[str, Sequence[str], None] = 'e6cf30432b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_history',
    sa.Column('history_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('consumer_id', sa.UUID(), nullable=True),
    sa.Column('session_token', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('product_title', sa.Text(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('verification_result', sa.String(length=50), nullable=False),
    sa.Column('matched_product_name', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('top_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('complaint_filed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints_table.complaint_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumer_account_table.consumer_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_history')
    # ### end Alembic commands ###
