"""add created_by to complaints

Revision ID: 2d8595200ca2
Revises: 300e7cad4b20
Create Date: 2026-07-27 20:14:08.960761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8595200ca2'
down_revision: Union[str, Sequence[str], None] = '300e7cad4b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'users', ['created_by'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'created_by')
    # ### end Alembic commands ###