"""add failed otp attempts to users table

Revision ID: 339777b482e7
Revises: 8cca08832ab6
Create Date: 2026-08-17 16:33:22.103952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339777b482e7'
down_revision: Union[str, Sequence[str], None] = '8cca08832ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_otp_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'failed_otp_attempts')
    # ### end Alembic commands ###
