"""add workspace_locations table

Revision ID: 685ad5eba676
Revises: ecfc0050a6a6
Create Date: 2026-09-21 22:01:48.162166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685ad5eba676'
down_revision: Union[str, Sequence[str], None] = 'ecfc0050a6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_locations',
    sa.Column('workspace_location_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agency', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('radius_meters', sa.Integer(), server_default=sa.text('500'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("agency IN ('FDA', 'LEA-CIDG')", name='ck_workspace_locations_agency'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('workspace_location_id'),
    sa.UniqueConstraint('agency', 'region_id', name='uq_workspace_locations_agency_region')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_locations')
    # ### end Alembic commands ###
