"""add sla reminder tracking columns to verification_requests

Revision ID: 6d1b99c391b7
Revises: 71ff80712e3c
Create Date: 2026-08-27 19:17:40.202853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1b99c391b7'
down_revision: Union[str, Sequence[str], None] = '71ff80712e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_requests', sa.Column('sla_reminder_1_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('verification_requests', sa.Column('sla_reminder_2_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('verification_requests', sa.Column('sla_breach_notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_requests', 'sla_breach_notified_at')
    op.drop_column('verification_requests', 'sla_reminder_2_sent_at')
    op.drop_column('verification_requests', 'sla_reminder_1_sent_at')
    # ### end Alembic commands ###
