"""create walkin intake drafts table

Revision ID: 73d66b052474
Revises: be6d53e93539
Create Date: 2026-07-10 18:47:44.571784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d66b052474'
down_revision: Union[str, Sequence[str], None] = 'be6d53e93539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walkin_intake_drafts',
    sa.Column('draft_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('saved_by', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('draft_status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('place_of_purchase', sa.Text(), nullable=True),
    sa.Column('date_of_purchase', sa.Date(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nature_of_complaint', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("draft_status IN ('incomplete', 'draft')", name='ck_walkin_intake_drafts_status'),
    sa.CheckConstraint("id_type IS NULL OR id_type IN ('philsys', 'passport', 'drivers_license', 'other')", name='ck_walkin_intake_drafts_id_type'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['saved_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('draft_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walkin_intake_drafts')
    # ### end Alembic commands ###
