"""create fda verification drafts table

Revision ID: 7db97c72b535
Revises: f5100677e978
Create Date: 2026-08-04 18:37:53.344474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db97c72b535'
down_revision: Union[str, Sequence[str], None] = 'f5100677e978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fda_verification_drafts',
    sa.Column('draft_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('saved_by', sa.UUID(), nullable=False),
    sa.Column('verification_request_id', sa.UUID(), nullable=False),
    sa.Column('draft_status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('draft_verification_status', sa.String(length=50), nullable=True),
    sa.Column('draft_cpr_number', sa.String(length=100), nullable=True),
    sa.Column('draft_cpr_expiry', sa.Date(), nullable=True),
    sa.Column('draft_response_notes', sa.Text(), nullable=True),
    sa.Column('draft_unregistered_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("draft_status IN ('incomplete', 'draft')", name='ck_fda_verification_drafts_status'),
    sa.CheckConstraint("draft_verification_status IS NULL OR draft_verification_status IN ('registered', 'unregistered')", name='ck_fda_verification_drafts_verification_status'),
    sa.ForeignKeyConstraint(['saved_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.request_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('draft_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fda_verification_drafts')
    # ### end Alembic commands ###
