"""add refresh token

Revision ID: 83794764a483
Revises: fbfe1f8c212f
Create Date: 2026-09-27 00:56:10.289098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83794764a483'
down_revision: Union[str, Sequence[str], None] = 'fbfe1f8c212f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumer_account_table', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('consumer_account_table', sa.Column('refresh_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumer_account_table', 'refresh_token_expires')
    op.drop_column('consumer_account_table', 'refresh_token')
    # ### end Alembic commands ###
