"""add target_reference and region_code to audit_logs

Revision ID: 8cca08832ab6
Revises: e6d78ec41572
Create Date: 2026-08-13 13:08:48.951184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cca08832ab6'
down_revision: Union[str, Sequence[str], None] = 'e6d78ec41572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('target_reference', sa.String(length=150), nullable=True))
    op.add_column('audit_logs', sa.Column('region_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'region_code')
    op.drop_column('audit_logs', 'target_reference')
    # ### end Alembic commands ###
