"""create registered products table

Revision ID: 9c7458a5fba6
Revises: c921dfac0b30
Create Date: 2026-07-10 17:34:06.659127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7458a5fba6'
down_revision: Union[str, Sequence[str], None] = 'c921dfac0b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_products',
    sa.Column('product_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('registration_status', sa.String(length=50), server_default=sa.text("'registered'"), nullable=False),
    sa.Column('date_registered', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('converted_from_advisory_id', sa.UUID(), nullable=True),
    sa.Column('marketplace_detection_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sbert_embedding', sa.Text(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("registration_status IN ('registered', 'unregistered')", name='ck_registered_products_status'),
    sa.CheckConstraint('(deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL)', name='ck_registered_products_soft_delete_pair'),
    sa.ForeignKeyConstraint(['added_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('registration_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registered_products')
    # ### end Alembic commands ###
