"""rename superadmin_notifications to admin_notifications, add agency and region_id

Revision ID: ac6fb99f83cd
Revises: 49b7c92fedb5
Create Date: 2026-09-09 17:22:45.961977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac6fb99f83cd'
down_revision: Union[str, Sequence[str], None] = '49b7c92fedb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the table itself — preserves all existing rows, unlike the
    # autogenerated drop_table/create_table pair.
    op.rename_table('superadmin_notifications', 'admin_notifications')

    # Postgres does NOT rename dependent constraints/indexes when a table
    # is renamed — do it explicitly so the DB matches the model's naming
    # convention and future autogenerate runs don't flag a phantom diff.
    op.execute('ALTER TABLE admin_notifications RENAME CONSTRAINT superadmin_notifications_pkey TO admin_notifications_pkey')
    op.execute('ALTER TABLE admin_notifications RENAME CONSTRAINT superadmin_notifications_recipient_id_fkey TO admin_notifications_recipient_id_fkey')
    op.execute('ALTER TABLE admin_notifications RENAME CONSTRAINT superadmin_notifications_related_user_id_fkey TO admin_notifications_related_user_id_fkey')
    op.execute('ALTER TABLE admin_notifications RENAME CONSTRAINT ck_superadmin_notifications_read_pair TO ck_admin_notifications_read_pair')
    op.execute('ALTER INDEX ix_superadmin_notifications_recipient_unread RENAME TO ix_admin_notifications_recipient_unread')

    # New columns — describe the EVENT's own agency/region, not the
    # recipient's (a national_admin has no region of their own). Both
    # nullable: national_admin-account events have neither.
    op.add_column('admin_notifications', sa.Column('agency', sa.String(length=10), nullable=True))
    op.add_column('admin_notifications', sa.Column('region_id', sa.UUID(), nullable=True))

    op.create_foreign_key(
        'admin_notifications_region_id_fkey',
        'admin_notifications', 'regions',
        ['region_id'], ['region_id'],
        ondelete='SET NULL',
    )
    op.create_check_constraint(
        'ck_admin_notifications_agency',
        'admin_notifications',
        "agency IS NULL OR agency IN ('FDA', 'LEA')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_admin_notifications_agency', 'admin_notifications', type_='check')
    op.drop_constraint('admin_notifications_region_id_fkey', 'admin_notifications', type_='foreignkey')
    op.drop_column('admin_notifications', 'region_id')
    op.drop_column('admin_notifications', 'agency')

    op.execute('ALTER INDEX ix_admin_notifications_recipient_unread RENAME TO ix_superadmin_notifications_recipient_unread')
    op.execute('ALTER TABLE admin_notifications RENAME CONSTRAINT ck_admin_notifications_read_pair TO ck_superadmin_notifications_read_pair')
    op.execute('ALTER TABLE admin_notifications RENAME CONSTRAINT admin_notifications_related_user_id_fkey TO superadmin_notifications_related_user_id_fkey')
    op.execute('ALTER TABLE admin_notifications RENAME CONSTRAINT admin_notifications_recipient_id_fkey TO superadmin_notifications_recipient_id_fkey')
    op.execute('ALTER TABLE admin_notifications RENAME CONSTRAINT admin_notifications_pkey TO superadmin_notifications_pkey')

    op.rename_table('admin_notifications', 'superadmin_notifications')
    # ### end Alembic commands ###
