"""create verification requests table

Revision ID: b375a49efe32
Revises: 10f115956c12
Create Date: 2026-07-10 18:55:29.364908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b375a49efe32'
down_revision: Union[str, Sequence[str], None] = '10f115956c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_requests',
    sa.Column('request_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('complaint_statement', sa.Text(), nullable=False),
    sa.Column('verification_request_status', sa.String(length=50), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default=sa.text("'standard'"), nullable=False),
    sa.Column('field_operation_notes', sa.Text(), nullable=True),
    sa.Column('field_operation_logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('field_operation_logged_by', sa.UUID(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_by', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('recalled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recalled_by', sa.UUID(), nullable=True),
    sa.Column('responded_by', sa.UUID(), nullable=True),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(verification_request_status != 'rejected') OR (rejection_reason IS NOT NULL)", name='ck_verification_requests_rejection_reason_required'),
    sa.CheckConstraint("priority IN ('standard', 'high', 'urgent', 'critical')", name='ck_verification_requests_priority'),
    sa.CheckConstraint("verification_request_status IN ('queued', 'pending', 'confirmed_registered', 'confirmed_unregistered', 'rejected', 'recalled')", name='ck_verification_requests_status'),
    sa.CheckConstraint('(recalled_at IS NULL AND recalled_by IS NULL) OR (recalled_at IS NOT NULL AND recalled_by IS NOT NULL)', name='ck_verification_requests_recalled_pair'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['field_operation_logged_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recalled_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reminder_sent_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responded_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_requests')
    # ### end Alembic commands ###
