"""create complaints table

Revision ID: b7aca9080cb5
Revises: 2128b7514b1a
Create Date: 2026-07-10 18:41:03.413278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7aca9080cb5'
down_revision: Union[str, Sequence[str], None] = '2128b7514b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('complaint_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_reference', sa.String(length=20), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('product_title', sa.Text(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_path', sa.Text(), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('consumer_description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('place_of_purchase', sa.Text(), nullable=True),
    sa.Column('date_of_purchase', sa.Date(), nullable=True),
    sa.Column('amount_paid', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('nature_of_complaint', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verification_result', sa.String(length=50), nullable=True),
    sa.Column('match_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'open'"), nullable=False),
    sa.Column('consumer_id', sa.UUID(), nullable=True),
    sa.Column('complainant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("source IN ('extension', 'walk_in')", name='ck_complaints_source'),
    sa.CheckConstraint("status IN ('open', 'under_review', 'takedown_requested', 'takedown_initiated', 'completed', 'dismissed')", name='ck_complaints_status'),
    sa.CheckConstraint('(deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL)', name='ck_complaints_soft_delete_pair'),
    sa.ForeignKeyConstraint(['complainant_id'], ['walkin_complainants.complainant_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumer_account_table.consumer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('complaint_id'),
    sa.UniqueConstraint('case_reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaints')
    # ### end Alembic commands ###
