"""create complaints status history

Revision ID: be6d53e93539
Revises: b7aca9080cb5
Create Date: 2026-07-10 18:44:40.026034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6d53e93539'
down_revision: Union[str, Sequence[str], None] = 'b7aca9080cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_status_history',
    sa.Column('history_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("new_status IN ('open', 'under_review', 'takedown_requested', 'takedown_initiated', 'completed', 'dismissed')", name='ck_complaint_status_history_new_status'),
    sa.CheckConstraint("previous_status IS NULL OR previous_status IN ('open', 'under_review', 'takedown_requested', 'takedown_initiated', 'completed', 'dismissed')", name='ck_complaint_status_history_previous_status'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint_status_history')
    # ### end Alembic commands ###
