"""add resend_requested_at to account_invitation_tokens

Revision ID: c2a9871de5a7
Revises: 0f77a280be74
Create Date: 2026-07-06 19:56:29.599832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a9871de5a7'
down_revision: Union[str, Sequence[str], None] = '0f77a280be74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_invitation_tokens', sa.Column('resend_requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_invitation_tokens', 'resend_requested_at')
    # ### end Alembic commands ###
