"""create unregistered advisories table

Revision ID: d8031b06f396
Revises: 9c7458a5fba6
Create Date: 2026-07-10 17:57:18.971256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8031b06f396'
down_revision: Union[str, Sequence[str], None] = '9c7458a5fba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unregistered_advisories',
    sa.Column('advisory_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('advisory_details', sa.Text(), nullable=True),
    sa.Column('advisory_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('converted_from_product_id', sa.UUID(), nullable=True),
    sa.Column('marketplace_detection_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sbert_embedding', sa.Text(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('(deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL)', name='ck_unregistered_advisories_soft_delete_pair'),
    sa.ForeignKeyConstraint(['added_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('advisory_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unregistered_advisories')
    # ### end Alembic commands ###
