"""create shared files table

Revision ID: e3dbcae97700
Revises: 01cfae4fbc76
Create Date: 2026-07-10 19:01:52.416361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3dbcae97700'
down_revision: Union[str, Sequence[str], None] = '01cfae4fbc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_files',
    sa.Column('file_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('recipient_agency', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recipient_agency IS NULL OR recipient_agency IN ('fda', 'lea')", name='ck_shared_files_recipient_agency'),
    sa.CheckConstraint('complaint_id IS NOT NULL OR recipient_agency IS NOT NULL', name='ck_shared_files_target_present'),
    sa.CheckConstraint('complaint_id IS NOT NULL OR region_id IS NOT NULL', name='ck_shared_files_region_present'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_files')
    # ### end Alembic commands ###
