"""create_complaints_table

Revision ID: e6cf30432b43
Revises: 768d4a5b15df
Create Date: 2026-07-03 19:43:11.748215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cf30432b43'
down_revision: Union[str, Sequence[str], None] = '768d4a5b15df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints_table',
    sa.Column('complaint_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_reference', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('product_title', sa.Text(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('matched_product_id', sa.UUID(), nullable=True, comment='The FK will be add later on'),
    sa.Column('verification_result', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'open'"), nullable=False),
    sa.Column('consumer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumer_account_table.consumer_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('complaint_id'),
    sa.UniqueConstraint('case_reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaints_table')
    # ### end Alembic commands ###
