"""create superadmin notifications table

Revision ID: e6d78ec41572
Revises: 6945bd24a302
Create Date: 2026-08-12 11:32:39.130986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d78ec41572'
down_revision: Union[str, Sequence[str], None] = '6945bd24a302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superadmin_notifications',
    sa.Column('notification_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_user_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_read = false AND read_at IS NULL) OR (is_read = true AND read_at IS NOT NULL)', name='ck_superadmin_notifications_read_pair'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('ix_superadmin_notifications_recipient_unread', 'superadmin_notifications', ['recipient_id', 'is_read', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_superadmin_notifications_recipient_unread', table_name='superadmin_notifications')
    op.drop_table('superadmin_notifications')
    # ### end Alembic commands ###
