"""create verification request drafts table

Revision ID: e77d2dd48a52
Revises: 73d66b052474
Create Date: 2026-07-10 18:50:18.040326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77d2dd48a52'
down_revision: Union[str, Sequence[str], None] = '73d66b052474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_request_drafts',
    sa.Column('draft_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('saved_by', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('draft_status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('notes_to_fda', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("draft_status IN ('incomplete', 'draft')", name='ck_verification_request_drafts_status'),
    sa.CheckConstraint("priority IS NULL OR priority IN ('standard', 'high', 'urgent', 'critical')", name='ck_verification_request_drafts_priority'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['saved_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('draft_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_request_drafts')
    # ### end Alembic commands ###
