"""move field_operation fields to complaints, add lea_acknowledged_at

Revision ID: efb55b2f5204
Revises: 339777b482e7
Create Date: 2026-08-18 19:46:06.879831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb55b2f5204'
down_revision: Union[str, Sequence[str], None] = '339777b482e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('field_operation_notes', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('field_operation_logged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('complaints', sa.Column('field_operation_logged_by', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('complaints_field_operation_logged_by_fkey'), 'complaints', 'users', ['field_operation_logged_by'], ['user_id'], ondelete='SET NULL')
    op.add_column('verification_requests', sa.Column('lea_acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('verification_requests_field_operation_logged_by_fkey'), 'verification_requests', type_='foreignkey')
    op.drop_column('verification_requests', 'field_operation_logged_at')
    op.drop_column('verification_requests', 'field_operation_logged_by')
    op.drop_column('verification_requests', 'field_operation_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_requests', sa.Column('field_operation_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verification_requests', sa.Column('field_operation_logged_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('verification_requests', sa.Column('field_operation_logged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('verification_requests_field_operation_logged_by_fkey'), 'verification_requests', 'users', ['field_operation_logged_by'], ['user_id'], ondelete='SET NULL')
    op.drop_column('verification_requests', 'lea_acknowledged_at')
    op.drop_constraint(op.f('complaints_field_operation_logged_by_fkey'), 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'field_operation_logged_by')
    op.drop_column('complaints', 'field_operation_logged_at')
    op.drop_column('complaints', 'field_operation_notes')
    # ### end Alembic commands ###
