"""create personnel_location_logs table

Revision ID: fbfe1f8c212f
Revises: 685ad5eba676
Create Date: 2026-09-21 22:11:31.114985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfe1f8c212f'
down_revision: Union[str, Sequence[str], None] = '685ad5eba676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel_location_logs',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('personnel_id', sa.UUID(), nullable=False),
    sa.Column('workspace_location_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('gps', 'ip')", name='ck_personnel_location_logs_source'),
    sa.ForeignKeyConstraint(['personnel_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_location_id'], ['workspace_locations.workspace_location_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personnel_location_logs')
    # ### end Alembic commands ###
