# backend/app/core/constants.py
class Role:
    NATIONAL_ADMIN = "national_admin"
    FDA_ADMIN = "fda_admin"
    LEA_ADMIN = "lea_admin"
    FDA_PERSONNEL = "fda_personnel"
    LEA_PERSONNEL = "lea_personnel"

    ADMIN_ROLES = {FDA_ADMIN, LEA_ADMIN}
    PERSONNEL_ROLES = {FDA_PERSONNEL, LEA_PERSONNEL}
    AGENCY_ROLES = {
        "FDA": {FDA_ADMIN, FDA_PERSONNEL},
        "LEA-CIDG": {LEA_ADMIN, LEA_PERSONNEL},
    }


class UserStatus:
    INVITED = "invited"
    PENDING_APPROVAL = "pending_approval"
    ACTIVE = "active"

    #to be worked on later, optional
    REJECTED = "rejected"
    RETURNED = "returned"


# Which complaint statuses are allowed to move to which other
# statuses, per source. Prevents accidentally skipping steps (e.g.
# jumping straight from 'open' to 'completed') or moving a complaint
# somewhere it can never leave (like 'dismissed' -> anything).
VALID_COMPLAINT_TRANSITIONS = {
    "extension": {
        "open": ["under_review", "dismissed"],
        "under_review": ["takedown_requested", "dismissed"],
        "takedown_requested": ["completed", "dismissed"],
        "completed": [],
        "dismissed": [],
    },
    "walk_in": {
        "open": ["under_review", "dismissed"],
        "under_review": ["takedown_requested", "dismissed", "open"], #added "open", so recalling a verification request can send the complaint back to Ready to Send
        "takedown_requested": ["takedown_initiated", "dismissed"],
        "takedown_initiated": ["completed", "dismissed"],
        "completed": [],
        "dismissed": [],
    },
}

class AuditAction:
    # Shared actions — across National Admin, Regional Admin, FDA, LEA-CIDG
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    LOGIN_FAILED = "LOGIN_FAILED"

    # Shared FDA/LEA-CIDG personnel actions (Region/Agency scoped) — Regional Admins auditlogs only under personnel tab
    PERSONNEL_REQUEST_PASSWORD_UPDATE = "PERSONNEL_REQUEST_PASSWORD_UPDATE"
    PERSONNEL_SELF_ACTIVATE = "PERSONNEL_SELF_ACTIVATE"
    UPDATE_COMPLAINT_STATUS = "UPDATE_COMPLAINT_STATUS"
    PERSONNEL_REQUEST_INVITE = "PERSONNEL_REQUEST_INVITE"

    # FDA actions (Region/Agency scoped) — Agency Admins tab only
    UPDATE_VERIFICATION_STATUS = "UPDATE_VERIFICATION_STATUS"
    CREATE_REGISTERED_PRODUCT = "CREATE_REGISTERED_PRODUCT"
    CONVERT_TO_REGISTERED_PRODUCT = "CONVERT_TO_REGISTERED_PRODUCT"
    UPDATE_REGISTERED_PRODUCT = "UPDATE_REGISTERED_PRODUCT"
    DELETE_REGISTERED_PRODUCT = "DELETE_REGISTERED_PRODUCT"
    CREATE_UNREGISTERED_ADVISORY = "CREATE_UNREGISTERED_ADVISORY"
    CONVERT_TO_UNREGISTERED_ADVISORY = "CONVERT_TO_UNREGISTERED_ADVISORY"
    UPDATE_UNREGISTERED_ADVISORY = "UPDATE_UNREGISTERED_ADVISORY"
    DELETE_UNREGISTERED_ADVISORY = "DELETE_UNREGISTERED_ADVISORY"

    # LEA-CIDG actions (Region/Agency scoped) — Agency Admins tab only
    CREATE_COMPLAINT_LOG = "CREATE_COMPLAINT_LOG"
    DELETE_COMPLAINT_LOG = "DELETE_COMPLAINT_LOG"
    UPDATE_COMPLAINT_LOG = "UPDATE_COMPLAINT_LOG"
    DELETE_VERIFICATION_REQUEST = "DELETE_VERIFICATION_REQUEST"
    CREATE_VERIFICATION_REQUEST = "CREATE_VERIFICATION_REQUEST"

    # National Admin actions — National Admins tab only
    INVITE_NATIONAL_ADMIN = "INVITE_NATIONAL_ADMIN"
    INVITE_NATIONAL_ADMIN_RESENT = "INVITE_NATIONAL_ADMIN_RESENT"
    NATIONAL_ADMIN_REQUEST_INVITE = "NATIONAL_ADMIN_REQUEST_INVITE"
    APPROVE_NATIONAL_ADMIN_ACCOUNT = "APPROVE_NATIONAL_ADMIN_ACCOUNT"
    SUSPEND_NATIONAL_ADMIN_ACCOUNT = "SUSPEND_NATIONAL_ADMIN_ACCOUNT"
    REACTIVATE_NATIONAL_ADMIN_ACCOUNT = "REACTIVATE_NATIONAL_ADMIN_ACCOUNT"
    DELETE_NATIONAL_ADMIN_ACCOUNT = "DELETE_NATIONAL_ADMIN_ACCOUNT"
    UNLOCK_NATIONAL_ADMIN_ACCOUNT = "UNLOCK_NATIONAL_ADMIN_ACCOUNT"
    UPDATE_NATIONAL_ADMIN_PASSWORD = "UPDATE_NATIONAL_ADMIN_PASSWORD"
    UPDATE_NATIONAL_ADMIN_INFORMATION = "UPDATE_NATIONAL_ADMIN_INFORMATION"

    # Regional Admin actions (Region/Agency scoped) — Regional Admins tab only
    INVITE_REGIONAL_ADMIN = "INVITE_REGIONAL_ADMIN"
    INVITE_REGIONAL_ADMIN_RESENT = "INVITE_REGIONAL_ADMIN_RESENT"
    REGIONAL_ADMIN_REQUEST_INVITE = "REGIONAL_ADMIN_REQUEST_INVITE"
    DELETE_REGIONAL_ADMIN_ACCOUNT = "DELETE_REGIONAL_ADMIN_ACCOUNT"
    UNLOCK_REGIONAL_ADMIN_ACCOUNT = "UNLOCK_REGIONAL_ADMIN_ACCOUNT"
    UPDATE_REGIONAL_ADMIN_PASSWORD = "UPDATE_REGIONAL_ADMIN_PASSWORD"
    UPDATE_REGIONAL_ADMIN_INFORMATION = "UPDATE_REGIONAL_ADMIN_INFORMATION"
    SET_WORKSPACE_LOCATION = "SET_WORKSPACE_LOCATION"
    UPDATE_WORKSPACE_LOCATION = "UPDATE_WORKSPACE_LOCATION"
    LOCATION_ANOMALY_DETECTED = "LOCATION_ANOMALY_DETECTED"

    # Personnel actions (Region/Agency scoped) — Regional Admins tab only
    INVITE_PERSONNEL = "INVITE_PERSONNEL"
    INVITE_PERSONNEL_RESENT = "INVITE_PERSONNEL_RESENT"
    SUSPEND_PERSONNEL_ACCOUNT = "SUSPEND_PERSONNEL_ACCOUNT"
    REACTIVATE_PERSONNEL_ACCOUNT = "REACTIVATE_PERSONNEL_ACCOUNT"
    DELETE_PERSONNEL_ACCOUNT = "DELETE_PERSONNEL_ACCOUNT"
    UNLOCK_PERSONNEL_ACCOUNT = "UNLOCK_PERSONNEL_ACCOUNT"
    UPDATE_PERSONNEL_PASSWORD = "UPDATE_PERSONNEL_PASSWORD"
    UPDATE_PERSONNEL_INFORMATION = "UPDATE_PERSONNEL_INFORMATION"

    # Shared National Admin + Regional Admin actions — shown on BOTH tabs
    APPROVE_REGIONAL_ADMIN_ACCOUNT = "APPROVE_REGIONAL_ADMIN_ACCOUNT"
    SUSPEND_REGIONAL_ADMIN_ACCOUNT = "SUSPEND_REGIONAL_ADMIN_ACCOUNT"
    REACTIVATE_REGIONAL_ADMIN_ACCOUNT = "REACTIVATE_REGIONAL_ADMIN_ACCOUNT"

    # System actions
    LOCK_PERSONNEL_ACCOUNT = "LOCK_PERSONNEL_ACCOUNT"
    LOCK_REGIONAL_ADMIN_ACCOUNT = "LOCK_REGIONAL_ADMIN_ACCOUNT"
    PENDING_REGIONAL_ADMIN_ACCOUNT = "PENDING_REGIONAL_ADMIN_ACCOUNT"
    PENDING_NATIONAL_ADMIN_ACCOUNT = "PENDING_NATIONAL_ADMIN_ACCOUNT"
    LOCK_NATIONAL_ADMIN_ACCOUNT = "LOCK_NATIONAL_ADMIN_ACCOUNT"